# Generated by Django 5.2.1 on 2025-06-14 08:11

import django.db.models.deletion
import letter.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='letter',
            name='date_arrival',
            field=models.DateField(validators=[letter.models.validate_today_date]),
        ),
        migrations.AlterField(
            model_name='letter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
