# Generated by Django 5.2.1 on 2025-05-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(height_field='300', upload_to='user_images', verbose_name='Аватарка', width_field='300'),
        ),
    ]
