# Generated by Django 5.2.1 on 2025-05-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50, unique=True)),
                ('what_do', models.TextField(max_length=1500)),
                ('how_did', models.TextField(max_length=1500)),
            ],
        ),
    ]
