# Generated by Django 5.2.1 on 2025-05-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_stack_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': 'Стек', 'verbose_name_plural': 'Стеки'},
        ),
        migrations.AlterField(
            model_name='stack',
            name='feature_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название функции'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='how_did',
            field=models.TextField(max_length=1500, verbose_name='Как реализовано'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='what_do',
            field=models.TextField(max_length=1500, verbose_name='Что делает'),
        ),
    ]
