# Generated by Django 5.2.1 on 2025-05-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_stack_options_alter_stack_feature_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'verbose_name': 'Фича', 'verbose_name_plural': 'Фичи'},
        ),
    ]
