# Generated by Django 5.2.1 on 2025-05-24 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_stack_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stack',
            options={'ordering': ['feature_name'], 'verbose_name': 'Фича', 'verbose_name_plural': 'Фичи'},
        ),
        migrations.AlterField(
            model_name='stack',
            name='how_did',
            field=models.TextField(verbose_name='Как реализовано'),
        ),
        migrations.AlterField(
            model_name='stack',
            name='what_do',
            field=models.TextField(verbose_name='Что делает'),
        ),
    ]
